[project]
id      = "example"
version = "0.1.0"
mach    = "^5.10"
src     = "src"
out     = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
default = true
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.linux-arm64]
isa = "aarch64"
os  = "linux"
abi = "aapcs64"

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[target.darwin-aarch64]
isa = "aarch64"
os  = "darwin"
abi = "aapcs64"

[profile.debug]
default = true
opt   = 0
debug = true
simd  = "scalarize"
vectorize     = false
float_reassoc = false

[profile.release]
opt   = 2
debug = false
simd  = "scalarize"
vectorize     = false
float_reassoc = false

[artifact.example]
default = true
kind    = "static"
entry   = "lib.mach"
out     = "lib/example"
targets = ["*"]
link    = []
need    = []

[dep.std]
git     = "https://github.com/briar-systems/mach-std"
version = "^7.0.2"
